### ISSUE TITLE
Support outputting only types

### ISSUE THREAD

**Issue by voxpelli** [uladkasach/sql-code-generator#33]
Similarly to how `graphql-code-generator` has the generation of resolvers separate from the types, I would like to be able to skip the output of the TypeScript query functions in this module.

Part of the reason: I'm using this in a JS-project through JSDoc, so typescript files won't be of any help.

The other part: I happily set up my own query functions 🙂

**Comment by uladkasach** [comment]
Great idea! I'll try and get some time to make this change this month - feel free to submit a PR if you need this sooner though
